name: build

on:
    push:
        branches: [main]
        paths:
            - .github/**
            - src/**
            - test/**
            - Makefile
    pull_request:
        branches: [main]
    workflow_dispatch:

env:
    SQLITE_RELEASE_YEAR: "2021"
    SQLITE_VERSION: "3360000"
    SQLITE_BRANCH: "3.36"

jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-20.04
                    - os: windows-latest
                    - os: macos-latest

        steps:
            - uses: actions/checkout@v2

            - name: Download SQLite sources
              shell: bash
              run: |
                  make prepare-dist
                  make download-sqlite
                  make download-external

            - name: Build for Linux
              if: matrix.os == 'ubuntu-20.04'
              run: |
                  make compile-linux
                  make test-all

            - name: Install MSYS2 and 'mingw-w64-i686-toolchain'
              if: matrix.os == 'windows-latest'
              uses: msys2/setup-msys2@v2
              with:
                  cache: true
                  install: mingw-w64-i686-toolchain
                  update: true

            - name: Build for Windows
              if: matrix.os == 'windows-latest'
              shell: bash
              run: |
                  $RUNNER_TEMP/msys64/msys2_shell.cmd -defterm -no-start -mingw32 -lc "mingw32-make compile-windows-x86"
                  make compile-windows

            - name: Build for macOS
              if: matrix.os == 'macos-latest'
              run: make compile-macos
