name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-2019
          - os: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare dist
        shell: bash
        run: |
          make download-sqlite
          make prepare-dist

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: make compile-linux

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: make compile-windows

      - name: Build for Windows 2019
        if: matrix.os == 'windows-2019'
        shell: bash
        run: make compile-windows-32

      - name: Build for macOS
        if: matrix.os == 'macos-latest'
        shell: bash
        run: make compile-macos

      - name: Run tests (on Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo curl -L https://github.com/mindreframer/sqlite/releases/download/0.7.1-3360/sqlite3-ubuntu --output /usr/local/bin/sqlite3
          sudo chmod +x /usr/local/bin/sqlite3
          sudo apt install nodejs yarn
          sudo npm install --global yarn
          pushd testrunner && yarn install && popd
          bin/test.sh CI
